
Vagrant.configure(2) do |config|
  config.vm.define "puppetmaster" do |puppetmaster|
    # Set VM memory and cpu specs
    puppetmaster.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    # Specify box and assign a hostname
    puppetmaster.vm.box_url = "http://kristianreese.com/stlpug/stlpug-master-centos-6-x64-virtualbox.box"
    puppetmaster.vm.box = "stlpug/puppetmaster"
    puppetmaster.vm.hostname = "puppetmaster.stlpug.com"

    # Network Configs
    puppetmaster.vm.network "private_network", ip: "10.10.10.10"
    puppetmaster.vm.network "forwarded_port", guest: 8140, host: 18140
    puppetmaster.vm.network "forwarded_port", guest: 443, host: 1443

  end
end
